"""empty message

Revision ID: e5146f02b359
Revises: ac1aa2dcd422
Create Date: 2025-04-27 22:37:29.242052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5146f02b359'
down_revision = 'ac1aa2dcd422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subsub_question', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('subsub_question')
        batch_op.drop_column('sub_question')

    # ### end Alembic commands ###
